### ISSUE TITLE
JSON and Demo

### ISSUE THREAD

**Issue by AmauryVanEspen** [goto-eof/minerva-europass#2]
Hi @goto-eof 
i'm not able to run the project,

could you please let me know if there is a demo of the project ?
i'm especially interested with compatibility with https://jsonresume.org/

Thank you

Regards
Amaury

**Comment by goto-eof** [comment]
> Hi @goto-eof 
> 
> i'm not able to run the project,
> 
> 
> 
> could you please let me know if there is a demo of the project ?
> 
> i'm especially interested with compatibility with https://jsonresume.org/
> 
> 
> 
> Thank you
> 
> 
> 
> Regards
> 
> Amaury

I answered on LinkedIn (DM).

Thank you,
Andrei
